In [3]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

import sklearn
from sklearn.linear_model import LinearRegression

In [24]:
dataset_train=pd.read_excel('MINI_PM_train.xlsx',header=None)
col_names = ['id','cycle','setting1','setting2','setting3','s1','s2','s3','s4','s5','s6','s7','s8','s9','s10','s11','s12','s13','s14','s15','s16','s17','s18','s19','s20','s21']
dataset_train.columns=col_names

dataset_train[['id','setting1','setting2','setting3','s1','s2','s3','s4','s5','s6','s7','s8','s9','s10','s11','s12','s13','s14','s15','s16','s17','s18','s19','s20','s21','cycle']]

col_names = ['id','setting1','setting2','setting3','s1','s2','s3','s4','s5','s6','s7','s8','s9','s10','s11','s12','s13','s14','s15','s16','s17','s18','s19','s20','s21','cycle']
dataset_train.columns=col_names

In [25]:
# 説明変数
X_multi = dataset_train.drop('cycle',1)

# 目的変数
Y_target = dataset_train.cycle

In [26]:
lreg = LinearRegression()

In [27]:
# モデルを作ります。
lreg.fit(X_multi,Y_target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
coeff_df = DataFrame(dataset_train.columns)
coeff_df

           0
0         id
1   setting1
2   setting2
3   setting3
4         s1
5         s2
6         s3
7         s4
8         s5
9         s6
10        s7
11        s8
12        s9
13       s10
14       s11
15       s12
16       s13
17       s14
18       s15
19       s16
20       s17
21       s18
22       s19
23       s20
24       s21
25     cycle

In [29]:
# 新しいDataFrameを作ります。
coeff_df = DataFrame(dataset_train.columns)
coeff_df.columns = ['Features']

#求められた係数を代入します。
coeff_df["Coefficient Estimate"] = pd.Series(lreg.coef_)

coeff_df

    Features  Coefficient Estimate
0         id         -7.460284e-05
1   setting1         -1.050981e-04
2   setting2         -1.577499e+00
3   setting3         -5.165140e+00
4         s1          3.697653e-12
5         s2         -1.705525e-12
6         s3         -1.174217e-02
7         s4         -7.606063e-04
8         s5         -4.064829e-04
9         s6          5.676015e-14
10        s7          6.760078e-01
11        s8          5.368139e-03
12        s9         -1.161424e-01
13       s10         -2.931916e-04
14       s11         -8.215650e-15
15       s12         -2.828287e-02
16       s13          1.995060e-02
17       s14         -3.150195e-01
18       s15         -3.829718e-04
19       s16         -1.107435e-01
20       s17          4.544521e-27
21       s18         -4.013767e-03
22       s19          0.000000e+00
23       s20          0.000000e+00
24       s21          5.052706e-02
25     cycle                   NaN

In [4]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,4))


plt.bar(Features, Coefficient Estimate)

SyntaxError: invalid syntax (<ipython-input-4-0c08beae5992>, line 6)